# PDAN Lightning Training Configuration
# Model configuration
model:
  name: "PDAN"
  num_stages: 1
  num_layers: 5
  num_channels: 512
  input_channels: 1024
  num_classes: 157

# Training configuration
training:
  batch_size: 8
  lr: 0.0001
  weight_decay: 0.0001
  max_epochs: 50
  warmup_epochs: 5
  grad_clip: 1.0
  optimizer: "adamw"  # adamw, adam, sgd
  scheduler: "cosine"  # cosine, plateau, none
  ap_type: "wap"  # wap, map

# Data configuration
data:
  mode: "rgb"  # rgb, flow, skeleton
  rgb_root: "/Path/to/charades_feat_rgb"
  flow_root: "/Path/to/charades_feat_flow"
  skeleton_root: "/Path/to/charades_feat_pose"
  train_split: "./data/charades.json"
  val_split: "./data/charades.json"
  num_workers: 8

# System configuration
system:
  gpus: 1
  nodes: 1
  precision: "16-mixed"  # 16-mixed, 32, bf16-mixed
  strategy: "auto"  # auto, ddp, ddp_spawn, etc.

# Logging configuration
logging:
  project_name: "PDAN"
  exp_name: "default"
  save_dir: "./lightning_logs"
  logger: "tensorboard"  # tensorboard, wandb, both
  wandb_project: "pdan-action-detection"

# Callbacks configuration
callbacks:
  early_stopping_patience: 15
  save_top_k: 3
  check_val_every_n_epoch: 1

# Debug configuration
debug:
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0

# Paths
paths:
  data_dir: "./data"
  log_dir: "./lightning_logs"
  ckpt_dir: "./checkpoints"
